# Automatically merge pull requests that:
# - are open
# - are not draft
# - pass CI checks
# - have at least 3 approvals

# Note:
# Pull requests that affect the `workflows` folder are NOT automerged for
# security reasons.
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # MERGE_ERROR_FAIL makes this workflow display as Failed
      # when GitHub denies merging for security reasons.
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_ERROR_FAIL: "true"
          MERGE_REQUIRED_APPROVALS: 3
